apiVersion: secrets.opensecrecy.org/v1alpha1
data:
  credentials: 6S0kOloWGbDk9t0wSlRIMux5uVgdvVz7D1K+ptLLZtP/hv0Yy5FravlJSHeRIP4EGbKe1ZkLM1anDZCsED+pHn5lW89UaJLfJl+SYUgW3DUmJJwDGla/7l8y
kind: EncryptedSecret
metadata:
  annotations:
    secrets.opensecrecy.org/provider: k8s
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: encryted-secrets
    app.kubernetes.io/name: encryptedsecret
    app.kubernetes.io/part-of: encryted-secrets
  name: aws-credentials
  namespace: default
