apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: rds-provider
spec:
  credentials:
    source: Secret
    secretRef:
      name: aws-credentials
      namespace: default
      key: credentials
