apiVersion: rds.aws.upbound.io/v1beta3
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1beta3/instance
  name: kcd-chennai
  namespace: default
spec:
  deletionPolicy: Delete
  forProvider:
    allocatedStorage: 20
    autoGeneratePassword: true
    autoMinorVersionUpgrade: true
    backupRetentionPeriod: 14
    backupWindow: 09:46-10:16
    dbName: example
    engine: postgres
    engineVersion: "16.6"
    instanceClass: db.t3.micro
    maintenanceWindow: Mon:00:00-Mon:03:00
    passwordSecretRef:
      key: password
      name: kcd-chennai-instance-1
      namespace: upbound-system
    publiclyAccessible: false
    region: us-west-1
    skipFinalSnapshot: true
    storageEncrypted: true
    storageType: gp2
    username: adminuser
    identifierPrefix: "kcdchennai-"
  providerConfigRef:
    name: rds-provider
  writeConnectionSecretToRef:
    name: kcd-chennai-instance-1
    namespace: default

